# Étape de build
FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Étape de production
FROM nginx:alpine
# Copier les fichiers compilés vers le dossier Nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Copier la configuration Nginx personnalisée si nécessaire (pour gérer le routing React)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
