import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:projeticem/theme/app_theme.dart';
import 'package:projeticem/screens/checklist_page.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:projeticem/models/anomaly.dart';
import 'package:projeticem/services/anomaly_service.dart';
import 'dart:async';
import 'dart:math';

/// Page d'inspection simulant un flux IA en plusieurs étapes
class InspectionPage extends StatefulWidget {
  final String? orderId;
  final String? orderReference;
  final String? cableReference;

  const InspectionPage({
    super.key,
    this.orderId,
    this.orderReference,
    this.cableReference,
  });

  @override
  State<InspectionPage> createState() => _InspectionPageState();
}

class _InspectionPageState extends State<InspectionPage> {
  CameraController? _controller;
  bool _isCameraReady = false;

  // Compteur dynamique de pièces inspectées
  int _partsInspectedCount = 0;

  // État de l'analyse IA
  bool _isProcessing = false;
  bool _showResult = false;
  Map<String, dynamic>? _stepResult;

  @override
  void initState() {
    super.initState();
    _initializeCamera();
  }

  Future<void> _initializeCamera() async {
    try {
      final cameras = await availableCameras();
      if (cameras.isEmpty) {
        _handleCameraError('Aucune caméra détectée. Mode pure simulation.');
        return;
      }

      _controller = CameraController(
        cameras.first,
        ResolutionPreset.medium,
        enableAudio: false,
        imageFormatGroup: ImageFormatGroup.jpeg,
      );

      await _controller!.initialize();
      if (mounted) {
        setState(() {
          _isCameraReady = true;
        });
      }
    } catch (e) {
      debugPrint('Camera error: $e');
      _handleCameraError('Erreur caméra: $e');
    }
  }

  void _handleCameraError(String message) {
    if (mounted) {
      setState(() {
        _isCameraReady = true; // On affiche quand même l'UI en mode dégradé (sans preview)
      });
      Future.delayed(const Duration(milliseconds: 100), () {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(message),
              backgroundColor: Colors.orange.shade800,
              duration: const Duration(seconds: 4),
            ),
          );
        }
      });
    }
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }

  /// Au clic sur le bouton Capture
  void _captureImage() async {
    if (_isProcessing || _showResult) return;

    setState(() {
      _isProcessing = true;
    });

    // Optionnel : figer la preview si supporté, sinon ça continue derrière
    try {
      await _controller?.pausePreview();
    } catch (_) {}

    // Simulation d'appel API de 1.5s
    await Future.delayed(const Duration(milliseconds: 1500));

    if (!mounted) return;

    // Simulation de résultat aléatoire
    final result = _generateSimulatedResult();

    // Si anomalie détectée, l'enregistrer dans Firestore
    if (result['status'] == 'NOK') {
      final anomaly = Anomaly(
        id: '', // Will be generated by Firestore
        type: result['label'],
        severity: result['confidence'] > 0.85 ? 'Critique' : 'Majeur',
        confidence: result['confidence'],
        location: 'Zone de capture #${_partsInspectedCount + 1}',
        cableId: widget.cableReference ?? 'SCAN-PLACEHOLDER',
        detectedAt: DateTime.now(),
      );
      
      AnomalyService().createAnomaly(anomaly).then((id) {
        debugPrint('Anomaly saved with ID: $id');
      }).catchError((e) {
        debugPrint('Failed to save anomaly: $e');
      });
    }

    setState(() {
      _isProcessing = false;
      _showResult = true;
      _stepResult = result;
      _partsInspectedCount++;
    });
  }

  /// Recommence une nouvelle analyse de composant
  void _nextComponent() async {
    setState(() {
      _showResult = false;
      _stepResult = null;
    });
    try {
      await _controller?.resumePreview();
    } catch (_) {}
  }

  void _finishInspection() async {
    setState(() {
      _isProcessing = true;
    });

    // Simuler la génération du rapport PDF
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            const SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                    color: Colors.white, strokeWidth: 2)),
            const SizedBox(width: 15),
            Text('Génération du rapport PDF automatique...',
                style: GoogleFonts.inter()),
          ],
        ),
        backgroundColor: AppTheme.primaryBlue,
        duration: const Duration(seconds: 2),
      ),
    );

    await Future.delayed(const Duration(seconds: 2));

    if (!mounted) return;

    final result = await Navigator.push<Map<String, dynamic>>(
      context,
      MaterialPageRoute(
        builder: (context) => ChecklistPage(
          orderId: widget.orderId,
          orderReference: widget.orderReference,
          cableReference: widget.cableReference,
        ),
      ),
    );

    if (mounted && result != null) {
      Navigator.pop(context, result);
    }
  }

  Map<String, dynamic> _generateSimulatedResult() {
    // Liste de défauts génériques applicables à n'importe quel composant
    final List<String> possibleDefects = [
      'Rayure détectée',
      'Déformation',
      'Élément mal positionné',
      'Composant manquant',
      'Couleur non conforme',
      'Trace de brûlure',
      'Fissure'
    ];

    final random = Random();
    // 70% chance que ce soit "OK" (sans défaut)
    if (random.nextDouble() > 0.3) {
      return {
        'status': 'OK',
        'label': 'Aucun défaut',
        'confidence': 0.85 + (random.nextDouble() * 0.14) // 85-99%
      };
    } else {
      return {
        'status': 'NOK',
        'label': possibleDefects[random.nextInt(possibleDefects.length)],
        'confidence': 0.70 + (random.nextDouble() * 0.25) // 70-95%
      };
    }
  }

  @override
  Widget build(BuildContext context) {
    if (!_isCameraReady) {
      return Scaffold(
        backgroundColor: Colors.black,
        body: const Center(
            child: CircularProgressIndicator(color: Colors.white)),
      );
    }

    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        fit: StackFit.expand,
        children: [
          _controller != null && _controller!.value.isInitialized
              ? CameraPreview(_controller!)
              : Container(color: const Color(0xFF1B2F4A)),
          
          if (!_showResult) _buildGuidageOverlay(),
          if (_showResult && _stepResult != null) _buildResultOverlay(),
          
          _buildTopBar(),
          if (widget.cableReference != null) _buildCableInfoBar(),
          
          _buildBottomControls(),
        ],
      ),
    );
  }

  Widget _buildTopBar() {
    return Positioned(
      top: 0, left: 0, right: 0,
      child: Container(
        padding: const EdgeInsets.only(top: 45, bottom: 15, left: 16, right: 16),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [Colors.black.withValues(alpha: 0.8), Colors.transparent],
          ),
        ),
        child: Row(
          children: [
            IconButton(
              icon: const Icon(Icons.close, color: Colors.white),
              onPressed: () => Navigator.pop(context),
            ),
            Expanded(
              child: Column(
                children: [
                  Text(
                    'INSPECTION IA',
                    style: GoogleFonts.inter(
                        color: Colors.white70,
                        fontSize: 11,
                        fontWeight: FontWeight.w600,
                        letterSpacing: 2),
                  ),
                  Text(
                    'COMPOSANT N°${_partsInspectedCount + (_showResult ? 0 : 1)}',
                    style: GoogleFonts.inter(
                        color: Colors.white,
                        fontSize: 20,
                        fontWeight: FontWeight.w800,
                        letterSpacing: 1.5),
                  ),
                ],
              ),
            ),
            const SizedBox(width: 48), // Balancing
          ],
        ),
      ),
    );
  }

  Widget _buildCableInfoBar() {
    return Positioned(
      top: 110, left: 16, right: 16,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        decoration: BoxDecoration(
          color: AppTheme.primaryBlue.withValues(alpha: 0.85),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Câble : ${widget.cableReference}',
                style: GoogleFonts.inter(
                    color: Colors.white,
                    fontWeight: FontWeight.w600,
                    fontSize: 13)),
          ],
        ),
      ),
    );
  }

  Widget _buildGuidageOverlay() {
    return Center(
      child: Container(
        width: 250,
        height: 250,
        decoration: BoxDecoration(
          border: Border.all(
            color: Colors.white.withValues(alpha: 0.3),
            width: 2,
          ),
          borderRadius: BorderRadius.circular(20),
        ),
        child: Center(
          child: _isProcessing 
          ? const CircularProgressIndicator(color: Colors.white)
          : Text(
              'Alignez ici',
              style: GoogleFonts.inter(
                color: Colors.white.withValues(alpha: 0.5),
                fontWeight: FontWeight.bold,
              ),
            ),
        ),
      ),
    );
  }

  Widget _buildResultOverlay() {
    final status = _stepResult!['status'] as String;
    final label = _stepResult!['label'] as String;
    final conf = _stepResult!['confidence'] as double;
    final isOk = status == 'OK';

    return Center(
      child: Container(
        width: 250,
        height: 250,
        decoration: BoxDecoration(
          border: Border.all(
            color: isOk ? AppTheme.successGreen : AppTheme.errorRed,
            width: 3,
          ),
          borderRadius: BorderRadius.circular(20),
          color: (isOk ? AppTheme.successGreen : AppTheme.errorRed).withValues(alpha: 0.1),
        ),
        child: Align(
          alignment: Alignment.bottomCenter,
          child: Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(vertical: 10),
            decoration: BoxDecoration(
              color: isOk ? AppTheme.successGreen : AppTheme.errorRed,
              borderRadius: const BorderRadius.only(
                  bottomLeft: Radius.circular(17),
                  bottomRight: Radius.circular(17)),
            ),
            child: Text(
              isOk ? 'OK — Conformité ${(conf * 100).toStringAsFixed(0)}%' : '$label (${(conf * 100).toStringAsFixed(0)}%)',
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(
                  color: Colors.white, fontWeight: FontWeight.w800, fontSize: 13),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildBottomControls() {
    final hasInspected = _partsInspectedCount > 0;

    return Positioned(
      bottom: 0, left: 0, right: 0,
      child: Container(
        padding: const EdgeInsets.fromLTRB(20, 30, 20, 40),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.bottomCenter,
            end: Alignment.topCenter,
            colors: [Colors.black.withValues(alpha: 0.9), Colors.transparent],
          ),
        ),
        child: Column(
          children: [
            // Texte d'état des inspections
            if (hasInspected)
              Padding(
                padding: const EdgeInsets.only(bottom: 25),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.inventory_rounded, color: AppTheme.successGreen, size: 16),
                    const SizedBox(width: 8),
                    Text(
                      '$_partsInspectedCount composant(s) inspecté(s)',
                      style: GoogleFonts.inter(color: Colors.white70, fontSize: 13),
                    ),
                  ],
                ),
              ),

            // Bouton de capture principal
            if (!_showResult && !_isProcessing)
              GestureDetector(
                onTap: _captureImage,
                child: Container(
                  width: 70, height: 70,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(color: Colors.white, width: 4),
                  ),
                  child: Container(
                    margin: const EdgeInsets.all(4),
                    decoration: const BoxDecoration(
                      color: Colors.white,
                      shape: BoxShape.circle,
                    ),
                  ),
                ),
              )
            else if (_isProcessing)
              const SizedBox(height: 70) // Espace vide
            else
              // Boutons "Continuer" ou "Terminer"
              Column(
                children: [
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton.icon(
                      onPressed: _nextComponent,
                      icon: const Icon(Icons.add_a_photo_rounded),
                      label: Text(
                        'Inspecter un autre composant',
                        style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w600),
                      ),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.white,
                        foregroundColor: Colors.black87,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                      ),
                    ),
                  ),
                  if (hasInspected) ...[
                    const SizedBox(height: 12),
                    SizedBox(
                      width: double.infinity,
                      child: OutlinedButton.icon(
                        onPressed: _finishInspection,
                        icon: const Icon(Icons.check_circle_rounded),
                        label: Text(
                          'Terminer & Générer le rapport',
                          style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w600),
                        ),
                        style: OutlinedButton.styleFrom(
                          foregroundColor: Colors.white,
                          side: const BorderSide(color: Colors.white54, width: 1.5),
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                        ),
                      ),
                    ),
                  ],
                ],
              ),
          ],
        ),
      ),
    );
  }
}
